server:
  port: 9527

spring:
  application:
    name: @artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: false #是否将服务id转换为小写
      routes:
        - id: providerServiceRouter    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://custom-logback-provider #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**         # 断言，路径相匹配的进行路由
            - After=2020-11-26T21:27:26.256+08:00[Asia/Shanghai]

        - id: consumerServiceRouter   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://custom-logback-consumer #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/**         # 断言，路径相匹配的进行路由
            - After=2020-11-25T22:42:23.608+08:00[Asia/Shanghai]
#            - Cookie=username,alex
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.somehost.org,**.anotherhost.org  # 匹配hostname
#            - Method=GET,POST
#            - Path=/red/{segment},/blue/{segment}
#            - Query=green
#            - RemoteAddr=192.168.1.1/24
#            - Weight=group1, 2
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: @artifactId@
    prefer-ip-address: true
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:7001/eureka
#负载均衡
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 1 # 当前服务的重试次数
  MaxAutoRetriesNextServer: 1 #切换相同 server 的次数